# Data Analysis Test

Use file `./ref/crop_data.csv` for input

Use `pandas` lib

Write your code and display readable result

In [1]:
import pandas as pd

In [ ]:
# read csv file

df = pd.read_csv("D:/git/DE_TEST/ref/crop_data.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   crop_year         11914 non-null  object 
 1   year              11914 non-null  int64  
 2   product           11914 non-null  object 
 3   province          11914 non-null  object 
 4   area_plant_rai    11769 non-null  float64
 5   area_harvest_rai  11728 non-null  float64
 6   production_ton    11692 non-null  float64
dtypes: float64(3), int64(1), object(3)
memory usage: 651.7+ KB


### Example Question

How many "ยางพารา" produced in whole country ("ทั้งประเทศ")

In [3]:
# How many "ยางพารา" produced in whole country ("ทั้งประเทศ")
new_df = df.loc[
    (df["product"] == "ยางพารา" ) &
    (df["province"] == "ทั้งประเทศ") 
]
sum(new_df["production_ton"])

47686839.0

### Question 1

How many "ข้าวนาปี" produced in "ยะลา" between year 2550 - 2553

In [4]:
Q1_df = df.loc[
    (df["product"] == "ข้าวนาปี" ) &
    (df["province"] == "ยะลา") &
    (df['year'] >= 2550) & 
    (df['year'] <= 2553)
]
Ans_Q1 = sum(Q1_df["production_ton"])
print('ข้าวนาปี produced in ยะลา between year 2550 - 2553 is',Ans_Q1, 'ตัน')

ข้าวนาปี produced in ยะลา between year 2550 - 2553 is 87707.0 ตัน


### Question 2

Calculate harvest rate of "ข้าวนาปี" in whole country

_harvest rate = area_harvest_rai / area_plant_rai_

In [5]:
# Write you code and display question 2 result here.
# replace with your code
Q2_df = df.loc[
    (df["product"] == "ข้าวนาปี" ) &
    (df["province"] == "ทั้งประเทศ")
]
area_plant_rai = sum(Q2_df["area_plant_rai"])
area_harvest_rai = sum(Q2_df["area_harvest_rai"])
harvest_rate = area_harvest_rai / area_plant_rai

print('Area harvest of ข้าวนาปี in whole country is', area_harvest_rai, 'ไร่')
print('Area plant of ข้าวนาปี in whole country is', area_plant_rai, 'ไร่')
print('Harvest rate of ข้าวนาปี in whole country is ร้อยละ', harvest_rate)

Area harvest of ข้าวนาปี in whole country is 730340255.0 ไร่
Area plant of ข้าวนาปี in whole country is 783456906.0 ไร่
Harvest rate of ข้าวนาปี in whole country is ร้อยละ 0.9322022046225986


### Question 3

Calculate total profit of "ข้าวโพดฝักอ่อน" produced in "ภาคเหนือ" from year 2555 to 2562
- profit rate in year 2555 - year 2559 is 50% (selling price is 50THB/kg.)
- profit rate in year 2560 - year 2562 is 30% (selling price is 120THB/kg.)
- assume all product was sold out every year.

In [6]:
# Write you code and display question 3 result here.
Q3_df = df[
    (df["product"] == "ข้าวโพดฝักอ่อน" ) &
    (df["province"] == "ภาคเหนือ") &
    (df['year'] >= 2555) & 
    (df['year'] <= 2562)
].copy()
Q3_df = Q3_df.reset_index(drop=True)

Q3_df['profit_thb'] = Q3_df.apply(
    lambda row: row['production_ton'] * 1000 * 50 * 0.5 if 2555 <= row['year'] <= 2559
    else row['production_ton'] * 1000 * 120 * 0.3 if 2560 <= row['year'] <= 2562
    else 0,  # return 0 f year out of range
    axis=1
)

Total_profit_Q3 = sum(Q3_df["profit_thb"])
print('Total profit of ข้าวโพดฝักอ่อน produced in ภาคเหนือ from year 2555 to 2562 is', Total_profit_Q3, 'THB')

Total profit of ข้าวโพดฝักอ่อน produced in ภาคเหนือ from year 2555 to 2562 is 5076935000.0 THB


### Question 4

Form question 3, display the dataframe with 'year', 'production_ton', 'income', 'profit_thb' column

In [7]:
# Write you code and display question 4 result here.
Q4_df = Q3_df.copy()
Q4_df['income'] = Q4_df.apply(
    lambda row: row['production_ton'] * 1000 * 50 if 2555 <= row['year'] <= 2559
    else row['production_ton'] * 1000 * 120 if 2560 <= row['year'] <= 2562
    else 0,  # return 0 f year out of range
    axis=1
)
print(Q4_df[['year', 'production_ton', 'income', 'profit_thb']])

   year  production_ton        income   profit_thb
0  2555         24741.0  1.237050e+09  618525000.0
1  2556         25371.0  1.268550e+09  634275000.0
2  2557         21788.0  1.089400e+09  544700000.0
3  2558         20499.0  1.024950e+09  512475000.0
4  2559         19332.0  9.666000e+08  483300000.0
5  2560         21329.0  2.559480e+09  767844000.0
6  2561         21757.0  2.610840e+09  783252000.0
7  2562         20349.0  2.441880e+09  732564000.0


### Question 5

We plan to invest in growing soybeans (ถั่วเหลือง) which province should we invest.

We looking for
- high protential area (high havest_rate)
- we want market share only 20% but production_ton should be more than 2000 in the past (2550 - 2562)


In [8]:
# Write you code and display question 5 result here.
# filter year and product
Q5_df = df[
    (df['product'] == "ถั่วเหลือง") &
    (df['year'] >= 2550) &
    (df['year'] <= 2562)
].copy()

# add column harvest_rate
Q5_df['harvest_rate'] = Q5_df['area_harvest_rai'] / Q5_df['area_plant_rai']

# Group the dataframe by province and add total_production, avg_harvest_rate column
Q5_df = Q5_df.groupby('province').agg(
    total_production=('production_ton', 'sum'),
    avg_harvest_rate=('harvest_rate', 'mean')
).reset_index()

# add column market share 20%
Q5_df['market_share'] = Q5_df['total_production'] * 0.2

#round column to two decimal for easier reading
Q5_df['avg_harvest_rate'] = Q5_df['avg_harvest_rate'].round(2)

#filter on given condition
Q5_df = Q5_df[
    (Q5_df['total_production'] > 2000) &
    (Q5_df['avg_harvest_rate'] > 0)
].sort_values(by=['avg_harvest_rate','market_share'], ascending=False)

print('Should invest in province',Q5_df['province'].iloc[0],'\n')
print(Q5_df.head(5))

Should invest in province แม่ฮ่องสอน 

      province  total_production  avg_harvest_rate  market_share
36  แม่ฮ่องสอน        216298.000              0.99    43259.6000
35        แพร่        124649.000              0.99    24929.8000
31    เชียงราย         68852.000              0.99    13770.4000
5   ฉะเชิงเทรา          8038.000              0.99     1607.6000
21       ลำพูน          3471.967              0.99      694.3934
